/*==============================================================*/
/* Table: SYS_DICT    基础字典                                 */
/* CREATE_DATE: 2016-05-14                                      */
/* CREATE_BY :  txb                                             */
/*==============================================================*/
-- 插入剂型字典
insert into sys_dict (id,label,value,type,description,sort) values (sys_guid(),'擦剂','LN','DRUG_FORM_DICT',' 药品剂型字典 ',10);
insert into sys_dict (id,label,value,type,description,sort) values (sys_guid(),'草药','CY','DRUG_FORM_DICT',' 药品剂型字典 ',10);
insert into sys_dict (id,label,value,type,description,sort) values (sys_guid(),'冲剂','GR','DRUG_FORM_DICT',' 药品剂型字典 ',10);
insert into sys_dict (id,label,value,type,description,sort) values (sys_guid(),'滴鼻剂','DN','DRUG_FORM_DICT',' 药品剂型字典 ',10);
insert into sys_dict (id,label,value,type,description,sort) values (sys_guid(),'滴耳剂','DH','DRUG_FORM_DICT',' 药品剂型字典 ',10);
insert into sys_dict (id,label,value,type,description,sort) values (sys_guid(),'滴剂','DJ','DRUG_FORM_DICT',' 药品剂型字典 ',10);
insert into sys_dict (id,label,value,type,description,sort) values (sys_guid(),'滴眼剂','DE','DRUG_FORM_DICT',' 药品剂型字典 ',10);
insert into sys_dict (id,label,value,type,description,sort) values (sys_guid(),'粉剂','PD','DRUG_FORM_DICT',' 药品剂型字典 ',10);
insert into sys_dict (id,label,value,type,description,sort) values (sys_guid(),'粉针','FZ','DRUG_FORM_DICT',' 药品剂型字典 ',10);
insert into sys_dict (id,label,value,type,description,sort) values (sys_guid(),'敷料','LY','DRUG_FORM_DICT',' 药品剂型字典 ',10);
insert into sys_dict (id,label,value,type,description,sort) values (sys_guid(),'干混悬剂','GH','DRUG_FORM_DICT',' 药品剂型字典 ',10);
insert into sys_dict (id,label,value,type,description,sort) values (sys_guid(),'膏剂','CR','DRUG_FORM_DICT',' 药品剂型字典 ',10);
insert into sys_dict (id,label,value,type,description,sort) values (sys_guid(),'混悬液','HX','DRUG_FORM_DICT',' 药品剂型字典 ',10);
insert into sys_dict (id,label,value,type,description,sort) values (sys_guid(),'胶囊','CP','DRUG_FORM_DICT',' 药品剂型字典 ',10);
insert into sys_dict (id,label,value,type,description,sort) values (sys_guid(),'胶丸','CL','DRUG_FORM_DICT',' 药品剂型字典 ',10);
insert into sys_dict (id,label,value,type,description,sort) values (sys_guid(),'浸膏','EX','DRUG_FORM_DICT',' 药品剂型字典 ',10);
insert into sys_dict (id,label,value,type,description,sort) values (sys_guid(),'颗粒','KL','DRUG_FORM_DICT',' 药品剂型字典 ',10);
insert into sys_dict (id,label,value,type,description,sort) values (sys_guid(),'口服液','KF','DRUG_FORM_DICT',' 药品剂型字典 ',10);
insert into sys_dict (id,label,value,type,description,sort) values (sys_guid(),'凝胶','GL','DRUG_FORM_DICT',' 药品剂型字典 ',10);
insert into sys_dict (id,label,value,type,description,sort) values (sys_guid(),'喷雾剂','SR','DRUG_FORM_DICT',' 药品剂型字典 ',10);
insert into sys_dict (id,label,value,type,description,sort) values (sys_guid(),'片剂','TA','DRUG_FORM_DICT',' 药品剂型字典 ',10);
insert into sys_dict (id,label,value,type,description,sort) values (sys_guid(),'溶液','SL','DRUG_FORM_DICT',' 药品剂型字典 ',10);
insert into sys_dict (id,label,value,type,description,sort) values (sys_guid(),'试剂','RE','DRUG_FORM_DICT',' 药品剂型字典 ',10);
insert into sys_dict (id,label,value,type,description,sort) values (sys_guid(),'试纸','IP','DRUG_FORM_DICT',' 药品剂型字典 ',10);
insert into sys_dict (id,label,value,type,description,sort) values (sys_guid(),'栓剂','SH','DRUG_FORM_DICT',' 药品剂型字典 ',10);
insert into sys_dict (id,label,value,type,description,sort) values (sys_guid(),'水济','SJ','DRUG_FORM_DICT',' 药品剂型字典 ',10);
insert into sys_dict (id,label,value,type,description,sort) values (sys_guid(),'水丸','SW','DRUG_FORM_DICT',' 药品剂型字典 ',10);
insert into sys_dict (id,label,value,type,description,sort) values (sys_guid(),'水针','SZ','DRUG_FORM_DICT',' 药品剂型字典 ',10);
insert into sys_dict (id,label,value,type,description,sort) values (sys_guid(),'素片','SP','DRUG_FORM_DICT',' 药品剂型字典 ',10);
insert into sys_dict (id,label,value,type,description,sort) values (sys_guid(),'糖浆剂','SY','DRUG_FORM_DICT',' 药品剂型字典 ',10);
insert into sys_dict (id,label,value,type,description,sort) values (sys_guid(),'糖丸','TW','DRUG_FORM_DICT',' 药品剂型字典 ',10);
insert into sys_dict (id,label,value,type,description,sort) values (sys_guid(),'贴剂','WE','DRUG_FORM_DICT',' 药品剂型字典 ',10);
insert into sys_dict (id,label,value,type,description,sort) values (sys_guid(),'丸剂','PL','DRUG_FORM_DICT',' 药品剂型字典 ',10);
insert into sys_dict (id,label,value,type,description,sort) values (sys_guid(),'液体','LQ','DRUG_FORM_DICT',' 药品剂型字典 ',10);
insert into sys_dict (id,label,value,type,description,sort) values (sys_guid(),'医材','YC','DRUG_FORM_DICT',' 药品剂型字典 ',10);
insert into sys_dict (id,label,value,type,description,sort) values (sys_guid(),'针剂','IJ','DRUG_FORM_DICT',' 药品剂型字典 ',10);
insert into sys_dict (id,label,value,type,description,sort) values (sys_guid(),'注射液','ZS','DRUG_FORM_DICT',' 药品剂型字典 ',10);
-- 插入药品毒理字典
insert into sys_dict (id,label,value,type,description,sort) values (sys_guid(),'精神五类','I','DRUG_TOXI_PROPERTY_DICT',' 药品毒理分类 ',10);
insert into sys_dict (id,label,value,type,description,sort) values (sys_guid(),'精神四类','G','DRUG_TOXI_PROPERTY_DICT',' 药品毒理分类 ',10);
insert into sys_dict (id,label,value,type,description,sort) values (sys_guid(),'巨毒药品','H','DRUG_TOXI_PROPERTY_DICT',' 药品毒理分类 ',10);
insert into sys_dict (id,label,value,type,description,sort) values (sys_guid(),'普通药品','A','DRUG_TOXI_PROPERTY_DICT',' 药品毒理分类 ',10);
insert into sys_dict (id,label,value,type,description,sort) values (sys_guid(),'麻醉药品','C','DRUG_TOXI_PROPERTY_DICT',' 药品毒理分类 ',10);
insert into sys_dict (id,label,value,type,description,sort) values (sys_guid(),'毒性药品','B','DRUG_TOXI_PROPERTY_DICT',' 药品毒理分类 ',10);
insert into sys_dict (id,label,value,type,description,sort) values (sys_guid(),'精神一类','D','DRUG_TOXI_PROPERTY_DICT',' 药品毒理分类 ',10);
insert into sys_dict (id,label,value,type,description,sort) values (sys_guid(),'精神二类','E','DRUG_TOXI_PROPERTY_DICT',' 药品毒理分类 ',10);
insert into sys_dict (id,label,value,type,description,sort) values (sys_guid(),'精神三类','F','DRUG_TOXI_PROPERTY_DICT',' 药品毒理分类 ',10);
--插入包装单位字典
insert into sys_dict(id,label,value,type,description,sort) values (sys_guid(),'把','Z3','spec_unit','包装单位',10);
insert into sys_dict(id,label,value,type,description,sort) values (sys_guid(),'板','G5','spec_unit','包装单位',10);
insert into sys_dict(id,label,value,type,description,sort) values (sys_guid(),'包','G4','spec_unit','包装单位',10);
insert into sys_dict(id,label,value,type,description,sort) values (sys_guid(),'本','J2','spec_unit','包装单位',10);
insert into sys_dict(id,label,value,type,description,sort) values (sys_guid(),'寸','G15','spec_unit','包装单位',10);
insert into sys_dict(id,label,value,type,description,sort) values (sys_guid(),'袋','G6','spec_unit','包装单位',10);
insert into sys_dict(id,label,value,type,description,sort) values (sys_guid(),'单位','J1','spec_unit','包装单位',10);
insert into sys_dict(id,label,value,type,description,sort) values (sys_guid(),'付','G12','spec_unit','包装单位',10);
insert into sys_dict(id,label,value,type,description,sort) values (sys_guid(),'个','G99','spec_unit','包装单位',10);
insert into sys_dict(id,label,value,type,description,sort) values (sys_guid(),'根','G22','spec_unit','包装单位',10);
insert into sys_dict(id,label,value,type,description,sort) values (sys_guid(),'鼓','Z7','spec_unit','包装单位',10);
insert into sys_dict(id,label,value,type,description,sort) values (sys_guid(),'盒','G2','spec_unit','包装单位',10);
insert into sys_dict(id,label,value,type,description,sort) values (sys_guid(),'卷','G16','spec_unit','包装单位',10);
insert into sys_dict(id,label,value,type,description,sort) values (sys_guid(),'克','F8','spec_unit','包装单位',10);
insert into sys_dict(id,label,value,type,description,sort) values (sys_guid(),'粒','G10','spec_unit','包装单位',10);
insert into sys_dict(id,label,value,type,description,sort) values (sys_guid(),'枚','G8','spec_unit','包装单位',10);
insert into sys_dict(id,label,value,type,description,sort) values (sys_guid(),'米','E2','spec_unit','包装单位',10);
insert into sys_dict(id,label,value,type,description,sort) values (sys_guid(),'喷','G88','spec_unit','包装单位',10);
insert into sys_dict(id,label,value,type,description,sort) values (sys_guid(),'批','批','spec_unit','包装单位',10);
insert into sys_dict(id,label,value,type,description,sort) values (sys_guid(),'片','G9','spec_unit','包装单位',10);
insert into sys_dict(id,label,value,type,description,sort) values (sys_guid(),'瓶','G3','spec_unit','包装单位',10);
insert into sys_dict(id,label,value,type,description,sort) values (sys_guid(),'人份','G87','spec_unit','包装单位',10);
insert into sys_dict(id,label,value,type,description,sort) values (sys_guid(),'套','G21','spec_unit','包装单位',10);
insert into sys_dict(id,label,value,type,description,sort) values (sys_guid(),'条','G20','spec_unit','包装单位',10);
insert into sys_dict(id,label,value,type,description,sort) values (sys_guid(),'贴','G13','spec_unit','包装单位',10);
insert into sys_dict(id,label,value,type,description,sort) values (sys_guid(),'听','G14','spec_unit','包装单位',10);
insert into sys_dict(id,label,value,type,description,sort) values (sys_guid(),'桶','G17','spec_unit','包装单位',10);
insert into sys_dict(id,label,value,type,description,sort) values (sys_guid(),'筒','G18','spec_unit','包装单位',10);
insert into sys_dict(id,label,value,type,description,sort) values (sys_guid(),'丸','G11','spec_unit','包装单位',10);
insert into sys_dict(id,label,value,type,description,sort) values (sys_guid(),'箱','G1','spec_unit','包装单位',10);
insert into sys_dict(id,label,value,type,description,sort) values (sys_guid(),'支','G7','spec_unit','包装单位',10);
insert into sys_dict(id,label,value,type,description,sort) values (sys_guid(),'轴','G19','spec_unit','包装单位',10);
insert into sys_dict(id,label,value,type,description,sort) values (sys_guid(),'亳升','B3','spec_unit','包装单位',10);
insert into sys_dict(id,label,value,type,description,sort) values (sys_guid(),'揿','G89','spec_unit','包装单位',10);
--插入计量单位字典
insert into sys_dict(id,label,value,type,description,sort) values (sys_guid(),'L','L','dose_unit','计量单位',10);
insert into sys_dict(id,label,value,type,description,sort) values (sys_guid(),'g','g','dose_unit','计量单位',10);
insert into sys_dict(id,label,value,type,description,sort) values (sys_guid(),'kg','kg','dose_unit','计量单位',10);
insert into sys_dict(id,label,value,type,description,sort) values (sys_guid(),'km','km','dose_unit','计量单位',10);
insert into sys_dict(id,label,value,type,description,sort) values (sys_guid(),'ml','ml','dose_unit','计量单位',10);
insert into sys_dict(id,label,value,type,description,sort) values (sys_guid(),'把','把','dose_unit','计量单位',10);
insert into sys_dict(id,label,value,type,description,sort) values (sys_guid(),'包','包','dose_unit','计量单位',10);
insert into sys_dict(id,label,value,type,description,sort) values (sys_guid(),'本','本','dose_unit','计量单位',10);
insert into sys_dict(id,label,value,type,description,sort) values (sys_guid(),'床','床','dose_unit','计量单位',10);
insert into sys_dict(id,label,value,type,description,sort) values (sys_guid(),'袋','袋','dose_unit','计量单位',10);
insert into sys_dict(id,label,value,type,description,sort) values (sys_guid(),'对','对','dose_unit','计量单位',10);
insert into sys_dict(id,label,value,type,description,sort) values (sys_guid(),'份','份','dose_unit','计量单位',10);
insert into sys_dict(id,label,value,type,description,sort) values (sys_guid(),'副','副','dose_unit','计量单位',10);
insert into sys_dict(id,label,value,type,description,sort) values (sys_guid(),'付','付','dose_unit','计量单位',10);
insert into sys_dict(id,label,value,type,description,sort) values (sys_guid(),'个','个','dose_unit','计量单位',10);
insert into sys_dict(id,label,value,type,description,sort) values (sys_guid(),'根','根','dose_unit','计量单位',10);
insert into sys_dict(id,label,value,type,description,sort) values (sys_guid(),'公斤','公斤','dose_unit','计量单位',10);
insert into sys_dict(id,label,value,type,description,sort) values (sys_guid(),'罐','罐','dose_unit','计量单位',10);
insert into sys_dict(id,label,value,type,description,sort) values (sys_guid(),'毫居','毫居','dose_unit','计量单位',10);
insert into sys_dict(id,label,value,type,description,sort) values (sys_guid(),'盒','盒','dose_unit','计量单位',10);
insert into sys_dict(id,label,value,type,description,sort) values (sys_guid(),'件','件','dose_unit','计量单位',10);
insert into sys_dict(id,label,value,type,description,sort) values (sys_guid(),'斤','斤','dose_unit','计量单位',10);
insert into sys_dict(id,label,value,type,description,sort) values (sys_guid(),'卷','卷','dose_unit','计量单位',10);
insert into sys_dict(id,label,value,type,description,sort) values (sys_guid(),'颗','颗','dose_unit','计量单位',10);
insert into sys_dict(id,label,value,type,description,sort) values (sys_guid(),'克','克','dose_unit','计量单位',10);
insert into sys_dict(id,label,value,type,description,sort) values (sys_guid(),'块','块','dose_unit','计量单位',10);
insert into sys_dict(id,label,value,type,description,sort) values (sys_guid(),'捆','捆','dose_unit','计量单位',10);
insert into sys_dict(id,label,value,type,description,sort) values (sys_guid(),'粒','粒','dose_unit','计量单位',10);
insert into sys_dict(id,label,value,type,description,sort) values (sys_guid(),'辆','辆','dose_unit','计量单位',10);
insert into sys_dict(id,label,value,type,description,sort) values (sys_guid(),'列','列','dose_unit','计量单位',10);
insert into sys_dict(id,label,value,type,description,sort) values (sys_guid(),'枚','枚','dose_unit','计量单位',10);
insert into sys_dict(id,label,value,type,description,sort) values (sys_guid(),'米','米','dose_unit','计量单位',10);
insert into sys_dict(id,label,value,type,description,sort) values (sys_guid(),'排','排','dose_unit','计量单位',10);
insert into sys_dict(id,label,value,type,description,sort) values (sys_guid(),'盘','盘','dose_unit','计量单位',10);
insert into sys_dict(id,label,value,type,description,sort) values (sys_guid(),'批','批','dose_unit','计量单位',10);
insert into sys_dict(id,label,value,type,description,sort) values (sys_guid(),'匹','匹','dose_unit','计量单位',10);
insert into sys_dict(id,label,value,type,description,sort) values (sys_guid(),'片','片','dose_unit','计量单位',10);
insert into sys_dict(id,label,value,type,description,sort) values (sys_guid(),'平方','平方','dose_unit','计量单位',10);
insert into sys_dict(id,label,value,type,description,sort) values (sys_guid(),'瓶','瓶','dose_unit','计量单位',10);
insert into sys_dict(id,label,value,type,description,sort) values (sys_guid(),'束','束','dose_unit','计量单位',10);
insert into sys_dict(id,label,value,type,description,sort) values (sys_guid(),'双','双','dose_unit','计量单位',10);
insert into sys_dict(id,label,value,type,description,sort) values (sys_guid(),'台','台','dose_unit','计量单位',10);
insert into sys_dict(id,label,value,type,description,sort) values (sys_guid(),'套','套','dose_unit','计量单位',10);
insert into sys_dict(id,label,value,type,description,sort) values (sys_guid(),'条','条','dose_unit','计量单位',10);
insert into sys_dict(id,label,value,type,description,sort) values (sys_guid(),'帖','帖','dose_unit','计量单位',10);
insert into sys_dict(id,label,value,type,description,sort) values (sys_guid(),'桶','桶','dose_unit','计量单位',10);
insert into sys_dict(id,label,value,type,description,sort) values (sys_guid(),'万支','万支','dose_unit','计量单位',10);
insert into sys_dict(id,label,value,type,description,sort) values (sys_guid(),'箱','箱','dose_unit','计量单位',10);
insert into sys_dict(id,label,value,type,description,sort) values (sys_guid(),'盏','盏','dose_unit','计量单位',10);
insert into sys_dict(id,label,value,type,description,sort) values (sys_guid(),'张','张','dose_unit','计量单位',10);
insert into sys_dict(id,label,value,type,description,sort) values (sys_guid(),'支','支','dose_unit','计量单位',10);
insert into sys_dict(id,label,value,type,description,sort) values (sys_guid(),'只','只','dose_unit','计量单位',10);
insert into sys_dict(id,label,value,type,description,sort) values (sys_guid(),'轴','轴','dose_unit','计量单位',10);
--插入药品贵重等级字典
insert into sys_dict(id,label,value,type,description,sort) values (sys_guid(),'普通','0','DRUG_PRECIOUS_FLAG_DICT','药品贵重等级字典',10);
insert into sys_dict(id,label,value,type,description,sort) values (sys_guid(),'一级贵重','1','DRUG_PRECIOUS_FLAG_DICT','药品贵重等级字典',10);
insert into sys_dict(id,label,value,type,description,sort) values (sys_guid(),'二级贵重','2','DRUG_PRECIOUS_FLAG_DICT','药品贵重等级字典',10);
insert into sys_dict(id,label,value,type,description,sort) values (sys_guid(),'三级贵重','3','DRUG_PRECIOUS_FLAG_DICT','药品贵重等级字典',10);
--插入价格类别字典
insert into sys_dict(id,label,value,type,description,sort) values (sys_guid(),'甲类','1','TENDER_PRICE_CLASS','价格类别字典',10);
insert into sys_dict(id,label,value,type,description,sort) values (sys_guid(),'乙类','2','TENDER_PRICE_CLASS','价格类别字典',10);
insert into sys_dict(id,label,value,type,description,sort) values (sys_guid(),'甲限','3','TENDER_PRICE_CLASS','价格类别字典',10);
insert into sys_dict(id,label,value,type,description,sort) values (sys_guid(),'乙限','4','TENDER_PRICE_CLASS','价格类别字典',10);
insert into sys_dict(id,label,value,type,description,sort) values (sys_guid(),'非','5','TENDER_PRICE_CLASS','价格类别字典',10);
insert into sys_dict(id,label,value,type,description,sort) values (sys_guid(),'门乙','6','TENDER_PRICE_CLASS','价格类别字典',10);
insert into sys_dict(id,label,value,type,description,sort) values (sys_guid(),'门甲','7','TENDER_PRICE_CLASS','价格类别字典',10);



