/**
 * Created by heren on 2016/6/23.
 */
/**
麻醉方式
 */
insert into SYS_DICT (ID, LABEL, VALUE, TYPE, DESCRIPTION, SORT, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE, REMARKS, DEL_FLAG, INPUT_CODE) values
('D52D14C80CCF4882A0C612F12C90A3SS', '基础', '1', 'ANAESTHESIA_DICT', '麻醉方式', 1, null, null, null, null, null, '0', 'JC');
insert into SYS_DICT (ID, LABEL, VALUE, TYPE, DESCRIPTION, SORT, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE, REMARKS, DEL_FLAG, INPUT_CODE) values
('D52D14C80CCF4882A0C612F12C90A4SS', '蛛网下腔阻滞麻醉', '2', 'ANAESTHESIA_DICT', '麻醉方式', 1, null, null, null, null, null, '0', 'ZWXQ');
insert into SYS_DICT (ID, LABEL, VALUE, TYPE, DESCRIPTION, SORT, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE, REMARKS, DEL_FLAG, INPUT_CODE) values
('D52D14C80CCF4882A0C612F12C90A5SS', '无', '3', 'ANAESTHESIA_DICT', '麻醉方式', 1, null, null, null, null, null, '0', 'W');
insert into SYS_DICT (ID, LABEL, VALUE, TYPE, DESCRIPTION, SORT, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE, REMARKS, DEL_FLAG, INPUT_CODE) values
('D52D14C80CCF4882A0C612F12C90A6SS', '体外麻醉', '4', 'ANAESTHESIA_DICT', '麻醉方式', 1, null, null, null, null, null, '0', 'TWMZ');
insert into SYS_DICT (ID, LABEL, VALUE, TYPE, DESCRIPTION, SORT, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE, REMARKS, DEL_FLAG, INPUT_CODE) values
('D52D14C80CCF4882A0C612F12C90A7SS', '全麻', '5', 'ANAESTHESIA_DICT', '麻醉方式', 1, null, null, null, null, null, '0', 'QM');
insert into SYS_DICT (ID, LABEL, VALUE, TYPE, DESCRIPTION, SORT, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE, REMARKS, DEL_FLAG, INPUT_CODE) values
('D52D14C80CCF4882A0C612F12C90A8SS', '硬膜外麻', '6', 'ANAESTHESIA_DICT', '麻醉方式', 1, null, null, null, null, null, '0', 'YMWM');
insert into SYS_DICT (ID, LABEL, VALUE, TYPE, DESCRIPTION, SORT, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE, REMARKS, DEL_FLAG, INPUT_CODE) values
('D52D14C80CCF4882A0C612F12C90A9SS', '颈丛阻滞', '7', 'ANAESTHESIA_DICT', '麻醉方式', 1, null, null, null, null, null, '0', 'JC');
insert into SYS_DICT (ID, LABEL, VALUE, TYPE, DESCRIPTION, SORT, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE, REMARKS, DEL_FLAG, INPUT_CODE) values
('D52D14C80CCF4882A0C612F12C90A10S', '臂丛阻滞', '8', 'ANAESTHESIA_DICT', '麻醉方式', 1, null, null, null, null, null, '0', 'BC');
insert into SYS_DICT (ID, LABEL, VALUE, TYPE, DESCRIPTION, SORT, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE, REMARKS, DEL_FLAG, INPUT_CODE) values
('D52D14C80CCF4882A0C612F12C90A311', '骶管阻滞', '9', 'ANAESTHESIA_DICT', '麻醉方式', 1, null, null, null, null, null, '0', 'DM');
insert into SYS_DICT (ID, LABEL, VALUE, TYPE, DESCRIPTION, SORT, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE, REMARKS, DEL_FLAG, INPUT_CODE) values
('D52D14C80CCF4882A0C612F12C90A322', '神经阻滞麻醉', '10', 'ANAESTHESIA_DICT', '麻醉方式', 1, null, null, null, null, null, '0', 'SJ');
/**
手术病情
 */
insert into SYS_DICT (ID, LABEL, VALUE, TYPE, DESCRIPTION, SORT, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE, REMARKS, DEL_FLAG, INPUT_CODE) values ('A96EE57041FA4ED3AC23CD1045F4DDRD', '危', '7', 'PATIENT_STATUS_DICT', '手术病情', 1, null, null, null, null, null, '0', 'W');
insert into SYS_DICT (ID, LABEL, VALUE, TYPE, DESCRIPTION, SORT, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE, REMARKS, DEL_FLAG, INPUT_CODE) values ('A96EE57041FA4ED3AC23CD1045F4EERE', '重', '8', 'PATIENT_STATUS_DICT', '手术病情', 2, null, null, null, null, null, '0', 'Z');
insert into SYS_DICT (ID, LABEL, VALUE, TYPE, DESCRIPTION, SORT, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE, REMARKS, DEL_FLAG, INPUT_CODE) values ('A96EE57041FA4ED3AC23CD1045FFDEFE', '一般', '9', 'PATIENT_STATUS_DICT', '手术病情', 3, null, null, null, null, null, '0', 'YB');

/**
手术等级
 */
insert into SYS_DICT (ID, LABEL, VALUE, TYPE, DESCRIPTION, SORT, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE, REMARKS, DEL_FLAG, INPUT_CODE) values
('D52D14C80CCF4882A0C612F12CQWEASD', '一级手术，风险较低、过程简单、技术难度低的普通手术', '7', 'OPERATION_SCALE_DICT', '手术等级', 1, null, null, null, null, null, '0', 'Y');
insert into SYS_DICT (ID, LABEL, VALUE, TYPE, DESCRIPTION, SORT, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE, REMARKS, DEL_FLAG, INPUT_CODE) values
('D52D14C80CCF4882A0C612F12ERTDFG', '二级手术，有一定风险、过程复杂程度一般、有一定技术难度的手术', '8', 'OPERATION_SCALE_DICT', '手术等级', 2, null, null, null, null, null, '0', 'R');
insert into SYS_DICT (ID, LABEL, VALUE, TYPE, DESCRIPTION, SORT, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE, REMARKS, DEL_FLAG, INPUT_CODE) values
('D52D14C80CCF4882A0C612F12RFVEDC', '三级手术，风险较高、过程较复杂、难度较大的手术', '9', 'OPERATION_SCALE_DICT', '手术等级', 3, null, null, null, null, null, '0', 'S');
insert into SYS_DICT (ID, LABEL, VALUE, TYPE, DESCRIPTION, SORT, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE, REMARKS, DEL_FLAG, INPUT_CODE) values
('D52D14C80CCF4882A0C612F12FGHVBG', '四级手术，风险高、过程复杂、难度大的重大手术', '10', 'OPERATION_SCALE_DICT', '手术等级', 4, null, null, null, null, null, '0', 'S');