/**
 * Created by heren on 2016/6/23.
 */

insert into SYS_DICT (ID, LABEL, VALUE, TYPE, DESCRIPTION, SORT, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE, REMARKS, DEL_FLAG, INPUT_CODE) values ('D52D14C80CCF4882A0C612F12C90A3SS', '麻醉方式', '1', 'ANAESTHESIA_DICT', '麻醉字典表', 1, null, null, null, null, null, '0', 'MZFS');
insert into SYS_DICT (ID, LABEL, VALUE, TYPE, DESCRIPTION, SORT, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE, REMARKS, DEL_FLAG, INPUT_CODE) values ('D52D14C80CCF4882A0C612F12C90DFE2', '麻醉方式', '1', 'OPERATION_SCALE_DICT', '手术等级字典', 2, null, null, null, null, null, '0', 'SSDJ');

