insert into SYS_DICT (ID, LABEL, VALUE, TYPE, DESCRIPTION, SORT, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE, REMARKS, DEL_FLAG, INPUT_CODE) values
('QWERTYU041FA4ED3AC23CDASDQERTFR', '危', '1', 'ADMISSION_SITUATION_DICT', '入院情况', 1, null, null, null, null, null, '0', 'W');
insert into SYS_DICT (ID, LABEL, VALUE, TYPE, DESCRIPTION, SORT, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE, REMARKS, DEL_FLAG, INPUT_CODE) values
('ASDFGHJ041FA4ED3AC23CDASDOPMU5G', '急', '2', 'ADMISSION_SITUATION_DICT', '入院情况', 2, null, null, null, null, null, '0', 'J');
insert into SYS_DICT (ID, LABEL, VALUE, TYPE, DESCRIPTION, SORT, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE, REMARKS, DEL_FLAG, INPUT_CODE) values
('ZXCVBNM041FA4ED3AC23CDASDOPMU5G', '一般', '2', 'ADMISSION_SITUATION_DICT', '入院情况', 2, null, null, null, null, null, '0', 'YB');