insert into SYS_DICT (ID, LABEL, VALUE, TYPE, DESCRIPTION, SORT, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE, REMARKS, DEL_FLAG, INPUT_CODE) values
('A96EE57041FA4ED3AC23CDASDQERTFR', '已婚', '1', 'MARRIAGE_DICT', '婚姻', 1, null, null, null, null, null, '0', 'YH');
insert into SYS_DICT (ID, LABEL, VALUE, TYPE, DESCRIPTION, SORT, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE, REMARKS, DEL_FLAG, INPUT_CODE) values
('A96EE57041FA4ED3AC23CDASDOPMU5G', '未婚', '2', 'MARRIAGE_DICT', '婚姻', 2, null, null, null, null, null, '0', 'WH');