
/**
输血方式
 */


insert into SYS_DICT (ID, LABEL, VALUE, TYPE, DESCRIPTION, SORT, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE, REMARKS, DEL_FLAG, INPUT_CODE) values
('ZXCVBNM041FA4ED3AC23CDASDOFVGTR', '血库供血', '1', 'TRANSFUSION_DICT', '输血方式', 1, null, null, null, null, null, '0', 'XKGX');

insert into SYS_DICT (ID, LABEL, VALUE, TYPE, DESCRIPTION, SORT, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE, REMARKS, DEL_FLAG, INPUT_CODE) values
('ZXCVBNM041FADCERAC23CDASDOPMU5G', '自体供血', '2', 'TRANSFUSION_DICT', '输血方式', 2, null, null, null, null, null, '0', 'ZTGX');