/**
病程记录
 */
insert into SYS_DICT (ID, LABEL, VALUE, TYPE, DESCRIPTION, SORT, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE, REMARKS, DEL_FLAG, INPUT_CODE) values
('ZXCVBNM041FA4ED3AC23CDASDO32158', '每日病程', '1', 'COURSE_RECORD_DICT', '病程记录', 1, null, null, null, null, null, '0', 'MRBC');
insert into SYS_DICT (ID, LABEL, VALUE, TYPE, DESCRIPTION, SORT, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE, REMARKS, DEL_FLAG, INPUT_CODE) values
('ZXCVBNM041FA4ED3AC23KLOIUO32158', '上级医师查房记录', '2', 'COURSE_RECORD_DICT', '病程记录', 2, null, null, null, null, null, '0', 'SJYSCF');
insert into SYS_DICT (ID, LABEL, VALUE, TYPE, DESCRIPTION, SORT, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE, REMARKS, DEL_FLAG, INPUT_CODE) values
('ZXCVBNM041FA4ED3AC23CDASDO32158', '阶段小结', '3', 'COURSE_RECORD_DICT', '病程记录',3, null, null, null, null, null, '0', 'JDXJ');