
/**
会诊类型
 */
insert into SYS_DICT (ID, LABEL, VALUE, TYPE, DESCRIPTION, SORT, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE, REMARKS, DEL_FLAG, INPUT_CODE) values
('POLIKEM041CV4ED3AC23CDASDO32158', '一般', '1', 'GROUP_TYPE', '会诊类型', 1, null, null, null, null, null, '0', 'YB');
insert into SYS_DICT (ID, LABEL, VALUE, TYPE, DESCRIPTION, SORT, CREATE_BY, CREATE_DATE, UPDATE_BY, UPDATE_DATE, REMARKS, DEL_FLAG, INPUT_CODE) values
('DCVB47M041RF4ED3AC23CDASDO32158', '紧急', '2', 'GROUP_TYPE', '会诊类型', 2, null, null, null, null, null, '0', 'JJ');