-- Create table
create table OPERATION_DICT
(
  id                varchar2(64),
  OPERATION_CODE     VARCHAR2(8),
  OPERATION_NAME     VARCHAR2(50) not null,
  OPERATION_SCALE    VARCHAR2(2),
  STD_INDICATOR      NUMBER(1),
  APPROVED_INDICATOR NUMBER(1),
  CREATE_DATE        DATE,
  INPUT_CODE         VARCHAR2(8),
  INPUT_CODE_WB      VARCHAR2(8),
  NM2                VARCHAR2(2),
  CREATE_USER        VARCHAR2(20),
  MEMO               VARCHAR2(60),
  OPERATION_TYPE     NUMBER(1)
);
-- Add comments to the table
comment on table OPERATION_DICT
  is '手术操作字典';
-- Add comments to the columns
comment on column OPERATION_DICT.OPERATION_CODE
  is '手术操作代码';
comment on column OPERATION_DICT.OPERATION_NAME
  is '手术操作名称';
comment on column OPERATION_DICT.OPERATION_SCALE
  is '手术等级';
comment on column OPERATION_DICT.STD_INDICATOR
  is '正名标志';
comment on column OPERATION_DICT.APPROVED_INDICATOR
  is '标准化标志';
comment on column OPERATION_DICT.CREATE_DATE
  is '创建日期';
comment on column OPERATION_DICT.INPUT_CODE
  is '输入码';
comment on column OPERATION_DICT.INPUT_CODE_WB
  is '五笔码';
comment on column OPERATION_DICT.NM2
  is '内码2';
-- Create/Recreate primary, unique and foreign key constraints
alter table OPERATION_DICT
  add constraint PK_OPERATION_DICT primary key (id);



insert into OPERATION_DICT (ID, OPERATION_CODE, OPERATION_NAME, OPERATION_SCALE, STD_INDICATOR, APPROVED_INDICATOR, CREATE_DATE, INPUT_CODE, INPUT_CODE_WB, NM2, CREATE_USER, MEMO, OPERATION_TYPE)
values ('4967D7055186465A86F41DC033353941', '1.411', '丘脑囊虫摘除术', null, 1, 1, null, 'QNNCZ', null, null, null, null, null);
insert into OPERATION_DICT (ID, OPERATION_CODE, OPERATION_NAME, OPERATION_SCALE, STD_INDICATOR, APPROVED_INDICATOR, CREATE_DATE, INPUT_CODE, INPUT_CODE_WB, NM2, CREATE_USER, MEMO, OPERATION_TYPE)
values ('B7EE971E3DDA4BA99700365080343466', '1.412', '丘脑少突胶质瘤切除术', null, 1, 1, null, 'QNSTJ', null, null, null, null, null);
insert into OPERATION_DICT (ID, OPERATION_CODE, OPERATION_NAME, OPERATION_SCALE, STD_INDICATOR, APPROVED_INDICATOR, CREATE_DATE, INPUT_CODE, INPUT_CODE_WB, NM2, CREATE_USER, MEMO, OPERATION_TYPE)
values ('A14D4FE0C0CA406297808CF47D4858C8', '1.42', '苍白球破坏术', null, 1, 1, null, 'CBQPH', null, null, null, null, null);
insert into OPERATION_DICT (ID, OPERATION_CODE, OPERATION_NAME, OPERATION_SCALE, STD_INDICATOR, APPROVED_INDICATOR, CREATE_DATE, INPUT_CODE, INPUT_CODE_WB, NM2, CREATE_USER, MEMO, OPERATION_TYPE)
values ('E111CCE4DBEE4D46B28046D813092508', '01.5', '其他脑和脑膜切除术或破坏术(01.5)', null, 1, 1, null, 'QTNHN', null, null, null, null, null);
insert into OPERATION_DICT (ID, OPERATION_CODE, OPERATION_NAME, OPERATION_SCALE, STD_INDICATOR, APPROVED_INDICATOR, CREATE_DATE, INPUT_CODE, INPUT_CODE_WB, NM2, CREATE_USER, MEMO, OPERATION_TYPE)
values ('A2F2CB35030C4A5A857911E5C6EE62A0', '1.51', '脑膜瘤切除术', null, 1, 1, null, 'NMLQC', null, null, null, null, null);
insert into OPERATION_DICT (ID, OPERATION_CODE, OPERATION_NAME, OPERATION_SCALE, STD_INDICATOR, APPROVED_INDICATOR, CREATE_DATE, INPUT_CODE, INPUT_CODE_WB, NM2, CREATE_USER, MEMO, OPERATION_TYPE)
values ('F1B3ED5567CB403DAC0E05337F77F12C', '1.53', '脑叶吸除术', null, 1, 1, null, 'NYXCS', null, null, null, null, null);
insert into OPERATION_DICT (ID, OPERATION_CODE, OPERATION_NAME, OPERATION_SCALE, STD_INDICATOR, APPROVED_INDICATOR, CREATE_DATE, INPUT_CODE, INPUT_CODE_WB, NM2, CREATE_USER, MEMO, OPERATION_TYPE)
values ('53B669400EE1414FB6D46CBE0E3A6B1C', '1.531', '颞叶切除术', null, 1, 1, null, 'NYQCS', null, null, null, null, null);
insert into OPERATION_DICT (ID, OPERATION_CODE, OPERATION_NAME, OPERATION_SCALE, STD_INDICATOR, APPROVED_INDICATOR, CREATE_DATE, INPUT_CODE, INPUT_CODE_WB, NM2, CREATE_USER, MEMO, OPERATION_TYPE)
values ('D747FC8B473F47B8A32CCEECDD940437', '1.59', '鞍区肿瘤切除术', null, 1, 1, null, 'AQZLQ', null, null, null, null, null);
insert into OPERATION_DICT (ID, OPERATION_CODE, OPERATION_NAME, OPERATION_SCALE, STD_INDICATOR, APPROVED_INDICATOR, CREATE_DATE, INPUT_CODE, INPUT_CODE_WB, NM2, CREATE_USER, MEMO, OPERATION_TYPE)
values ('B833A1B8077B42CB9CE75C1FF48B2009', '1.591', '侧脑室肿瘤切除术', null, 1, 1, null, 'CNSZL', null, null, null, null, null);
insert into OPERATION_DICT (ID, OPERATION_CODE, OPERATION_NAME, OPERATION_SCALE, STD_INDICATOR, APPROVED_INDICATOR, CREATE_DATE, INPUT_CODE, INPUT_CODE_WB, NM2, CREATE_USER, MEMO, OPERATION_TYPE)
values ('C39916767078421A9E39F4CBAF5AAD27', '1.592', '大脑半球肿瘤切除术', null, 1, 1, null, 'DNBQZ', null, null, null, null, null);
insert into OPERATION_DICT (ID, OPERATION_CODE, OPERATION_NAME, OPERATION_SCALE, STD_INDICATOR, APPROVED_INDICATOR, CREATE_DATE, INPUT_CODE, INPUT_CODE_WB, NM2, CREATE_USER, MEMO, OPERATION_TYPE)
values ('04FF9A4E666441C1BCC8FAF85AB8792E', '1.593', '第三脑室肿瘤切除术', null, 1, 1, null, 'DSNSZ', null, null, null, null, null);
insert into OPERATION_DICT (ID, OPERATION_CODE, OPERATION_NAME, OPERATION_SCALE, STD_INDICATOR, APPROVED_INDICATOR, CREATE_DATE, INPUT_CODE, INPUT_CODE_WB, NM2, CREATE_USER, MEMO, OPERATION_TYPE)
values ('64ED935C11FE4425B0F4298F8E45F13F', '1.594', '第四脑室肿瘤切除术', null, 1, 1, null, 'DSNSZ0', null, null, null, null, null);
insert into OPERATION_DICT (ID, OPERATION_CODE, OPERATION_NAME, OPERATION_SCALE, STD_INDICATOR, APPROVED_INDICATOR, CREATE_DATE, INPUT_CODE, INPUT_CODE_WB, NM2, CREATE_USER, MEMO, OPERATION_TYPE)
values ('BB69F99F5F7F441D80BA26190404C2EC', '1.595', '基底节肿瘤切除术', null, 1, 1, null, 'JDJZL', null, null, null, null, null);
insert into OPERATION_DICT (ID, OPERATION_CODE, OPERATION_NAME, OPERATION_SCALE, STD_INDICATOR, APPROVED_INDICATOR, CREATE_DATE, INPUT_CODE, INPUT_CODE_WB, NM2, CREATE_USER, MEMO, OPERATION_TYPE)
values ('3015EC8091E1441A8B4260D13B07926D', '1.596', '颅内胆质瘤切除术', null, 1, 1, null, 'LNDZL', null, null, null, null, null);
insert into OPERATION_DICT (ID, OPERATION_CODE, OPERATION_NAME, OPERATION_SCALE, STD_INDICATOR, APPROVED_INDICATOR, CREATE_DATE, INPUT_CODE, INPUT_CODE_WB, NM2, CREATE_USER, MEMO, OPERATION_TYPE)
values ('9D2F5A4C96AA43D59E54CD08E4392082', '1.597', '颅内肿瘤切除术', null, 1, 1, null, 'LNZLQ', null, null, null, null, null);
insert into OPERATION_DICT (ID, OPERATION_CODE, OPERATION_NAME, OPERATION_SCALE, STD_INDICATOR, APPROVED_INDICATOR, CREATE_DATE, INPUT_CODE, INPUT_CODE_WB, NM2, CREATE_USER, MEMO, OPERATION_TYPE)
values ('B48C587F46B74DFD80024CD604593245', '1.598', '颅咽管瘤切除术', null, 1, 1, null, 'LYGLQ', null, null, null, null, null);
insert into OPERATION_DICT (ID, OPERATION_CODE, OPERATION_NAME, OPERATION_SCALE, STD_INDICATOR, APPROVED_INDICATOR, CREATE_DATE, INPUT_CODE, INPUT_CODE_WB, NM2, CREATE_USER, MEMO, OPERATION_TYPE)
values ('12D10F33DA73485C803F924883354894', '1.599', '脑干肿瘤切除术', null, 1, 1, null, 'NGZLQ', null, null, null, null, null);
insert into OPERATION_DICT (ID, OPERATION_CODE, OPERATION_NAME, OPERATION_SCALE, STD_INDICATOR, APPROVED_INDICATOR, CREATE_DATE, INPUT_CODE, INPUT_CODE_WB, NM2, CREATE_USER, MEMO, OPERATION_TYPE)
values ('337DEC5B92B94C43B53EFC12DF3A245C', '01.59A', '脑囊肿切除术', null, 1, 1, null, 'NNZQC0', null, null, null, null, null);
insert into OPERATION_DICT (ID, OPERATION_CODE, OPERATION_NAME, OPERATION_SCALE, STD_INDICATOR, APPROVED_INDICATOR, CREATE_DATE, INPUT_CODE, INPUT_CODE_WB, NM2, CREATE_USER, MEMO, OPERATION_TYPE)
values ('6D456C3D22784141A20BF8C34220753F', '01.59B', '脑清创缝合术', null, 1, 1, null, 'NQCFH', null, null, null, null, null);
insert into OPERATION_DICT (ID, OPERATION_CODE, OPERATION_NAME, OPERATION_SCALE, STD_INDICATOR, APPROVED_INDICATOR, CREATE_DATE, INPUT_CODE, INPUT_CODE_WB, NM2, CREATE_USER, MEMO, OPERATION_TYPE)
values ('FDD57EAADD06487F99A3348CAEC843FD', '01.59C', '脑肉芽肿切除术', null, 1, 1, null, 'NRYZQ', null, null, null, null, null);
insert into OPERATION_DICT (ID, OPERATION_CODE, OPERATION_NAME, OPERATION_SCALE, STD_INDICATOR, APPROVED_INDICATOR, CREATE_DATE, INPUT_CODE, INPUT_CODE_WB, NM2, CREATE_USER, MEMO, OPERATION_TYPE)
values ('7330EE7FBDDE4FB6B5A73FF943DB1B26', '01.59D', '脑肿瘤切除术', null, 1, 1, null, 'NZLQC', null, null, null, null, null);
insert into OPERATION_DICT (ID, OPERATION_CODE, OPERATION_NAME, OPERATION_SCALE, STD_INDICATOR, APPROVED_INDICATOR, CREATE_DATE, INPUT_CODE, INPUT_CODE_WB, NM2, CREATE_USER, MEMO, OPERATION_TYPE)
values ('8C706D41DEEA4613B92F1C7F0D5D07E3', '01.59E', '小脑半球肿瘤切除术', null, 1, 1, null, 'XNBQZ', null, null, null, null, null);
insert into OPERATION_DICT (ID, OPERATION_CODE, OPERATION_NAME, OPERATION_SCALE, STD_INDICATOR, APPROVED_INDICATOR, CREATE_DATE, INPUT_CODE, INPUT_CODE_WB, NM2, CREATE_USER, MEMO, OPERATION_TYPE)
values ('79676A6BF8E349BD8CBB48CF5B437054', '01.59F', '小脑肿瘤切除术', null, 1, 1, null, 'XNZLQ', null, null, null, null, null);
insert into OPERATION_DICT (ID, OPERATION_CODE, OPERATION_NAME, OPERATION_SCALE, STD_INDICATOR, APPROVED_INDICATOR, CREATE_DATE, INPUT_CODE, INPUT_CODE_WB, NM2, CREATE_USER, MEMO, OPERATION_TYPE)
values ('D0A39AD2D8674951BD808ADADE507380', '01.0', '颅穿刺术(01.0)', null, 1, 1, null, 'LCCS', null, null, null, null, null);
insert into OPERATION_DICT (ID, OPERATION_CODE, OPERATION_NAME, OPERATION_SCALE, STD_INDICATOR, APPROVED_INDICATOR, CREATE_DATE, INPUT_CODE, INPUT_CODE_WB, NM2, CREATE_USER, MEMO, OPERATION_TYPE)
values ('B5FAB1E5FEB84DF2A0FB1C0646E6F4FA', '01.59G', '胼胝体肿瘤切除术', null, 1, 1, null, 'PZTZL', null, null, null, null, null);
insert into OPERATION_DICT (ID, OPERATION_CODE, OPERATION_NAME, OPERATION_SCALE, STD_INDICATOR, APPROVED_INDICATOR, CREATE_DATE, INPUT_CODE, INPUT_CODE_WB, NM2, CREATE_USER, MEMO, OPERATION_TYPE)
values ('D2EC4A95C32E43C598F93143845BCB7A', '01.6', '颅的病损切除术(01.6)', null, 1, 1, null, 'LDBSQ', null, null, null, null, null);
insert into OPERATION_DICT (ID, OPERATION_CODE, OPERATION_NAME, OPERATION_SCALE, STD_INDICATOR, APPROVED_INDICATOR, CREATE_DATE, INPUT_CODE, INPUT_CODE_WB, NM2, CREATE_USER, MEMO, OPERATION_TYPE)
values ('E04DA31C7DEE4D2CAE5294121C6DC8D2', '1.6', '颅病害切除术', null, 1, 1, null, 'LBHQC', null, null, null, null, null);
insert into OPERATION_DICT (ID, OPERATION_CODE, OPERATION_NAME, OPERATION_SCALE, STD_INDICATOR, APPROVED_INDICATOR, CREATE_DATE, INPUT_CODE, INPUT_CODE_WB, NM2, CREATE_USER, MEMO, OPERATION_TYPE)
values ('30C1EA3181E340D98C2A5DC696287DD6', '1.601', '颅骨肿瘤切除术', null, 1, 1, null, 'LGZLQ', null, null, null, null, null);
insert into OPERATION_DICT (ID, OPERATION_CODE, OPERATION_NAME, OPERATION_SCALE, STD_INDICATOR, APPROVED_INDICATOR, CREATE_DATE, INPUT_CODE, INPUT_CODE_WB, NM2, CREATE_USER, MEMO, OPERATION_TYPE)
values ('B11F32C60AC34DFC85CCB7CDF107EDEF', '1.602', '颅内血管瘤切除', null, 1, 1, null, 'LNXGL', null, null, null, null, null);
insert into OPERATION_DICT (ID, OPERATION_CODE, OPERATION_NAME, OPERATION_SCALE, STD_INDICATOR, APPROVED_INDICATOR, CREATE_DATE, INPUT_CODE, INPUT_CODE_WB, NM2, CREATE_USER, MEMO, OPERATION_TYPE)
values ('8951A2C46AAE4B3A885058B0CDAF3278', '02', '其他颅、脑和脑膜的手术(02)', null, 1, 1, null, 'QTLNH', null, null, null, null, null);
insert into OPERATION_DICT (ID, OPERATION_CODE, OPERATION_NAME, OPERATION_SCALE, STD_INDICATOR, APPROVED_INDICATOR, CREATE_DATE, INPUT_CODE, INPUT_CODE_WB, NM2, CREATE_USER, MEMO, OPERATION_TYPE)
values ('D31ED2A4B101461289D40BC48803E019', '02.0', '颅成形术(02.0)', null, 1, 1, null, 'LCXS', null, null, null, null, null);
insert into OPERATION_DICT (ID, OPERATION_CODE, OPERATION_NAME, OPERATION_SCALE, STD_INDICATOR, APPROVED_INDICATOR, CREATE_DATE, INPUT_CODE, INPUT_CODE_WB, NM2, CREATE_USER, MEMO, OPERATION_TYPE)
values ('B25606F5490145DFB2A2BFEF35B18FBC', '2.02', '颅骨骨折复位', null, 1, 1, null, 'LGGZF', null, null, null, null, null);
insert into OPERATION_DICT (ID, OPERATION_CODE, OPERATION_NAME, OPERATION_SCALE, STD_INDICATOR, APPROVED_INDICATOR, CREATE_DATE, INPUT_CODE, INPUT_CODE_WB, NM2, CREATE_USER, MEMO, OPERATION_TYPE)
values ('8D0E9C087B7E432BACFAA0D88C1A5EC6', '2.021', '颅骨骨折复位术', null, 1, 1, null, 'LGGZF0', null, null, null, null, null);
insert into OPERATION_DICT (ID, OPERATION_CODE, OPERATION_NAME, OPERATION_SCALE, STD_INDICATOR, APPROVED_INDICATOR, CREATE_DATE, INPUT_CODE, INPUT_CODE_WB, NM2, CREATE_USER, MEMO, OPERATION_TYPE)
values ('F866473698CD477C81568C9A17105F3C', '2.05', '颅骨硅钢修补术', null, 1, 1, null, 'LGGGX', null, null, null, null, null);
insert into OPERATION_DICT (ID, OPERATION_CODE, OPERATION_NAME, OPERATION_SCALE, STD_INDICATOR, APPROVED_INDICATOR, CREATE_DATE, INPUT_CODE, INPUT_CODE_WB, NM2, CREATE_USER, MEMO, OPERATION_TYPE)
values ('9D05361C2035413D8EF6E05762392627', '2.051', '颅骨其它材料修补术', null, 1, 1, null, 'LGQTC', null, null, null, null, null);
insert into OPERATION_DICT (ID, OPERATION_CODE, OPERATION_NAME, OPERATION_SCALE, STD_INDICATOR, APPROVED_INDICATOR, CREATE_DATE, INPUT_CODE, INPUT_CODE_WB, NM2, CREATE_USER, MEMO, OPERATION_TYPE)
values ('098B7F9D5FDA4F26B3027ED09EDC4C17', '2.052', '颅骨有机玻璃修补术', null, 1, 1, null, 'LGYJB', null, null, null, null, null);
insert into OPERATION_DICT (ID, OPERATION_CODE, OPERATION_NAME, OPERATION_SCALE, STD_INDICATOR, APPROVED_INDICATOR, CREATE_DATE, INPUT_CODE, INPUT_CODE_WB, NM2, CREATE_USER, MEMO, OPERATION_TYPE)
values ('75461FB86F9643ECA23F4EB72A5CDE20', '2.053', '颅骨钛钢片修补术', null, 1, 1, null, 'LGTGP', null, null, null, null, null);
insert into OPERATION_DICT (ID, OPERATION_CODE, OPERATION_NAME, OPERATION_SCALE, STD_INDICATOR, APPROVED_INDICATOR, CREATE_DATE, INPUT_CODE, INPUT_CODE_WB, NM2, CREATE_USER, MEMO, OPERATION_TYPE)
values ('71E4A10413224417A093FECC995C9126', '2.06', '开放性颅骨缝合', null, 1, 1, null, 'KFXLG', null, null, null, null, null);
insert into OPERATION_DICT (ID, OPERATION_CODE, OPERATION_NAME, OPERATION_SCALE, STD_INDICATOR, APPROVED_INDICATOR, CREATE_DATE, INPUT_CODE, INPUT_CODE_WB, NM2, CREATE_USER, MEMO, OPERATION_TYPE)
values ('C6BDED46603142B2ACA2D3BD0310E722', '2.061', '颅缝再造术', null, 1, 1, null, 'LFZZS', null, null, null, null, null);
insert into OPERATION_DICT (ID, OPERATION_CODE, OPERATION_NAME, OPERATION_SCALE, STD_INDICATOR, APPROVED_INDICATOR, CREATE_DATE, INPUT_CODE, INPUT_CODE_WB, NM2, CREATE_USER, MEMO, OPERATION_TYPE)
values ('79DD8A8407A0483B8C84AA5E35866FE4', '2.062', '颅骨成形术', null, 1, 1, null, 'LGCXS', null, null, null, null, null);
insert into OPERATION_DICT (ID, OPERATION_CODE, OPERATION_NAME, OPERATION_SCALE, STD_INDICATOR, APPROVED_INDICATOR, CREATE_DATE, INPUT_CODE, INPUT_CODE_WB, NM2, CREATE_USER, MEMO, OPERATION_TYPE)
values ('EEFEB37E04004515BA599F016C2B6EA6', '2.063', '颅骨修补术', null, 1, 1, null, 'LGXBS', null, null, null, null, null);
insert into OPERATION_DICT (ID, OPERATION_CODE, OPERATION_NAME, OPERATION_SCALE, STD_INDICATOR, APPROVED_INDICATOR, CREATE_DATE, INPUT_CODE, INPUT_CODE_WB, NM2, CREATE_USER, MEMO, OPERATION_TYPE)
values ('E2092913381B4EC2A7D29BC610E03633', '2.064', '颅窝成形术', null, 1, 1, null, 'LWCXS', null, null, null, null, null);
insert into OPERATION_DICT (ID, OPERATION_CODE, OPERATION_NAME, OPERATION_SCALE, STD_INDICATOR, APPROVED_INDICATOR, CREATE_DATE, INPUT_CODE, INPUT_CODE_WB, NM2, CREATE_USER, MEMO, OPERATION_TYPE)
values ('23D2D089CC6A4996B3A883A8EFECF836', '2.065', '帽状颞浅岛状筋膜瓣移植术', null, 1, 1, null, 'MZNQD', null, null, null, null, null);
insert into OPERATION_DICT (ID, OPERATION_CODE, OPERATION_NAME, OPERATION_SCALE, STD_INDICATOR, APPROVED_INDICATOR, CREATE_DATE, INPUT_CODE, INPUT_CODE_WB, NM2, CREATE_USER, MEMO, OPERATION_TYPE)
values ('3C821FA2C8F5460E864DB9C6BC584273', '02.1', '脑膜修补术(02.1)', null, 1, 1, null, 'NMXBS', null, null, null, null, null);
insert into OPERATION_DICT (ID, OPERATION_CODE, OPERATION_NAME, OPERATION_SCALE, STD_INDICATOR, APPROVED_INDICATOR, CREATE_DATE, INPUT_CODE, INPUT_CODE_WB, NM2, CREATE_USER, MEMO, OPERATION_TYPE)
values ('C404E116A1AA4388A8A891720CD7E6C4', '2.11', '颅硬膜修补缝合术', null, 1, 1, null, 'LYMXB', null, null, null, null, null);
insert into OPERATION_DICT (ID, OPERATION_CODE, OPERATION_NAME, OPERATION_SCALE, STD_INDICATOR, APPROVED_INDICATOR, CREATE_DATE, INPUT_CODE, INPUT_CODE_WB, NM2, CREATE_USER, MEMO, OPERATION_TYPE)
values ('BC5D4DD8075A48D1AB4648AF3104A2F9', '2.12', '颅裂脑膜脑膨出修补术', null, 1, 1, null, 'LLNMN', null, null, null, null, null);
insert into OPERATION_DICT (ID, OPERATION_CODE, OPERATION_NAME, OPERATION_SCALE, STD_INDICATOR, APPROVED_INDICATOR, CREATE_DATE, INPUT_CODE, INPUT_CODE_WB, NM2, CREATE_USER, MEMO, OPERATION_TYPE)
values ('FB89254AABCA462198F12BCBE1EA36B0', '2.121', '颅裂脑膜膨出修补术', null, 1, 1, null, 'LLNMP', null, null, null, null, null);
insert into OPERATION_DICT (ID, OPERATION_CODE, OPERATION_NAME, OPERATION_SCALE, STD_INDICATOR, APPROVED_INDICATOR, CREATE_DATE, INPUT_CODE, INPUT_CODE_WB, NM2, CREATE_USER, MEMO, OPERATION_TYPE)
values ('4F0C2994AE6A4780881E0B7E7D476C29', '2.122', '脑脊液漏修补术', null, 1, 1, null, 'NJYLX', null, null, null, null, null);
insert into OPERATION_DICT (ID, OPERATION_CODE, OPERATION_NAME, OPERATION_SCALE, STD_INDICATOR, APPROVED_INDICATOR, CREATE_DATE, INPUT_CODE, INPUT_CODE_WB, NM2, CREATE_USER, MEMO, OPERATION_TYPE)
values ('99711DDBFCDB4B47953262F53DDFE6A3', '2.123', '脑膜修补', null, 1, 1, null, 'NMXB', null, null, null, null, null);
insert into OPERATION_DICT (ID, OPERATION_CODE, OPERATION_NAME, OPERATION_SCALE, STD_INDICATOR, APPROVED_INDICATOR, CREATE_DATE, INPUT_CODE, INPUT_CODE_WB, NM2, CREATE_USER, MEMO, OPERATION_TYPE)
values ('4A851F0388864E8793DBCA7131C79660', '2.14', '侧脑室脉络丛切除灼烧术', null, 1, 1, null, 'CNSML', null, null, null, null, null);
insert into OPERATION_DICT (ID, OPERATION_CODE, OPERATION_NAME, OPERATION_SCALE, STD_INDICATOR, APPROVED_INDICATOR, CREATE_DATE, INPUT_CODE, INPUT_CODE_WB, NM2, CREATE_USER, MEMO, OPERATION_TYPE)
values ('BA95C7619C16462686ED0028A3989844', '2.141', '第三脑室脉络丛切除灼烧术', null, 1, 1, null, 'DSNSM', null, null, null, null, null);
insert into OPERATION_DICT (ID, OPERATION_CODE, OPERATION_NAME, OPERATION_SCALE, STD_INDICATOR, APPROVED_INDICATOR, CREATE_DATE, INPUT_CODE, INPUT_CODE_WB, NM2, CREATE_USER, MEMO, OPERATION_TYPE)
values ('8E9CF10D15D24B5BAC15936F473BCEFE', '2.142', '第四脑室脉络丛切除灼烧术', null, 1, 1, null, 'DSNSM0', null, null, null, null, null);
insert into OPERATION_DICT (ID, OPERATION_CODE, OPERATION_NAME, OPERATION_SCALE, STD_INDICATOR, APPROVED_INDICATOR, CREATE_DATE, INPUT_CODE, INPUT_CODE_WB, NM2, CREATE_USER, MEMO, OPERATION_TYPE)
values ('8697194417B94CE3830445A76DB099B4', '2.143', '脉络丛切除灼烧术', null, 1, 1, null, 'MLCQC', null, null, null, null, null);
insert into OPERATION_DICT (ID, OPERATION_CODE, OPERATION_NAME, OPERATION_SCALE, STD_INDICATOR, APPROVED_INDICATOR, CREATE_DATE, INPUT_CODE, INPUT_CODE_WB, NM2, CREATE_USER, MEMO, OPERATION_TYPE)
values ('90FD818982BC465DB0AFABC2A6913457', '02.2', '脑室造口术(02.2)', null, 1, 1, null, 'NSZKS', null, null, null, null, null);
insert into OPERATION_DICT (ID, OPERATION_CODE, OPERATION_NAME, OPERATION_SCALE, STD_INDICATOR, APPROVED_INDICATOR, CREATE_DATE, INPUT_CODE, INPUT_CODE_WB, NM2, CREATE_USER, MEMO, OPERATION_TYPE)
values ('D77D9EAFF616484C87FC4816E86388A4', '2.2', '第三脑室造瘘术', null, 1, 1, null, 'DSNSZ1', null, null, null, null, null);
insert into OPERATION_DICT (ID, OPERATION_CODE, OPERATION_NAME, OPERATION_SCALE, STD_INDICATOR, APPROVED_INDICATOR, CREATE_DATE, INPUT_CODE, INPUT_CODE_WB, NM2, CREATE_USER, MEMO, OPERATION_TYPE)
values ('753DCFFB3B734EAE93476C0F58AF0646', '2.201', '脑室造瘘术', null, 1, 1, null, 'NSZLS', null, null, null, null, null);
insert into OPERATION_DICT (ID, OPERATION_CODE, OPERATION_NAME, OPERATION_SCALE, STD_INDICATOR, APPROVED_INDICATOR, CREATE_DATE, INPUT_CODE, INPUT_CODE_WB, NM2, CREATE_USER, MEMO, OPERATION_TYPE)
values ('B78449C6082F4AC9BBF46B6D52A72130', '02.3', '颅外脑室分流术(02.3)', null, 1, 1, null, 'LWNSF', null, null, null, null, null);
insert into OPERATION_DICT (ID, OPERATION_CODE, OPERATION_NAME, OPERATION_SCALE, STD_INDICATOR, APPROVED_INDICATOR, CREATE_DATE, INPUT_CODE, INPUT_CODE_WB, NM2, CREATE_USER, MEMO, OPERATION_TYPE)
values ('DB92DA496AB24E70A51660FC37C6CC6F', '2.32', '脑室-颈静脉分流术', null, 1, 1, null, 'NSJJM', null, null, null, null, null);
insert into OPERATION_DICT (ID, OPERATION_CODE, OPERATION_NAME, OPERATION_SCALE, STD_INDICATOR, APPROVED_INDICATOR, CREATE_DATE, INPUT_CODE, INPUT_CODE_WB, NM2, CREATE_USER, MEMO, OPERATION_TYPE)
values ('C0C50261055E4514B175461522471769', '2.321', '脑室-颈外动脉分流术', null, 1, 1, null, 'NSJWD', null, null, null, null, null);
insert into OPERATION_DICT (ID, OPERATION_CODE, OPERATION_NAME, OPERATION_SCALE, STD_INDICATOR, APPROVED_INDICATOR, CREATE_DATE, INPUT_CODE, INPUT_CODE_WB, NM2, CREATE_USER, MEMO, OPERATION_TYPE)
values ('6C65FDB7787F44BAB978AFF90C919975', '2.322', '脑室-心房分流术', null, 1, 1, null, 'NSXFF', null, null, null, null, null);
insert into OPERATION_DICT (ID, OPERATION_CODE, OPERATION_NAME, OPERATION_SCALE, STD_INDICATOR, APPROVED_INDICATOR, CREATE_DATE, INPUT_CODE, INPUT_CODE_WB, NM2, CREATE_USER, MEMO, OPERATION_TYPE)
values ('BE8642DCACAA4E19BE39B03C469309DC', '2.323', '脑室心房分流术', null, 1, 1, null, 'NSXFF0', null, null, null, null, null);
insert into OPERATION_DICT (ID, OPERATION_CODE, OPERATION_NAME, OPERATION_SCALE, STD_INDICATOR, APPROVED_INDICATOR, CREATE_DATE, INPUT_CODE, INPUT_CODE_WB, NM2, CREATE_USER, MEMO, OPERATION_TYPE)
values ('9FAB89A1AC014787817EAD5A668A79B0', '2.33', '脑室-胸导管分流术', null, 1, 1, null, 'NSXDG', null, null, null, null, null);
insert into OPERATION_DICT (ID, OPERATION_CODE, OPERATION_NAME, OPERATION_SCALE, STD_INDICATOR, APPROVED_INDICATOR, CREATE_DATE, INPUT_CODE, INPUT_CODE_WB, NM2, CREATE_USER, MEMO, OPERATION_TYPE)
values ('545601486E074D6591C08E23EF3E1AFE', '2.34', '脑室-腹腔分流术', null, 1, 1, null, 'NSFQF', null, null, null, null, null);
insert into OPERATION_DICT (ID, OPERATION_CODE, OPERATION_NAME, OPERATION_SCALE, STD_INDICATOR, APPROVED_INDICATOR, CREATE_DATE, INPUT_CODE, INPUT_CODE_WB, NM2, CREATE_USER, MEMO, OPERATION_TYPE)
values ('1F6958DE20A54AD99E419F828FDBDAD9', '2.35', '脑室-膀胱分流术', null, 1, 1, null, 'NSBGF', null, null, null, null, null);
insert into OPERATION_DICT (ID, OPERATION_CODE, OPERATION_NAME, OPERATION_SCALE, STD_INDICATOR, APPROVED_INDICATOR, CREATE_DATE, INPUT_CODE, INPUT_CODE_WB, NM2, CREATE_USER, MEMO, OPERATION_TYPE)
values ('2EFF2FCF860E411FB356308F58575739', '2.39', '脑室-矢状窦分流术', null, 1, 1, null, 'NSSZD', null, null, null, null, null);
insert into OPERATION_DICT (ID, OPERATION_CODE, OPERATION_NAME, OPERATION_SCALE, STD_INDICATOR, APPROVED_INDICATOR, CREATE_DATE, INPUT_CODE, INPUT_CODE_WB, NM2, CREATE_USER, MEMO, OPERATION_TYPE)
values ('F5C8D56B45124157873B1B001C59F385', '2.391', '脑室-小脑分流术', null, 1, 1, null, 'NSXNF', null, null, null, null, null);
insert into OPERATION_DICT (ID, OPERATION_CODE, OPERATION_NAME, OPERATION_SCALE, STD_INDICATOR, APPROVED_INDICATOR, CREATE_DATE, INPUT_CODE, INPUT_CODE_WB, NM2, CREATE_USER, MEMO, OPERATION_TYPE)
values ('511442E51ECC429B8907F30AE36BEAC1', '2.392', '脑室-小脑延髓池分流术', null, 1, 1, null, 'NSXNY', null, null, null, null, null);
insert into OPERATION_DICT (ID, OPERATION_CODE, OPERATION_NAME, OPERATION_SCALE, STD_INDICATOR, APPROVED_INDICATOR, CREATE_DATE, INPUT_CODE, INPUT_CODE_WB, NM2, CREATE_USER, MEMO, OPERATION_TYPE)
values ('A2C5300554F344D585D4342E0625B9B3', '2.393', '脑室-蛛网膜下腔分流术', null, 1, 1, null, 'NSZWM', null, null, null, null, null);
insert into OPERATION_DICT (ID, OPERATION_CODE, OPERATION_NAME, OPERATION_SCALE, STD_INDICATOR, APPROVED_INDICATOR, CREATE_DATE, INPUT_CODE, INPUT_CODE_WB, NM2, CREATE_USER, MEMO, OPERATION_TYPE)
values ('2C9A7118157840F19A355C36CCB4B1DC', '2.394', '脑室-胼胝体周围池分流术', null, 1, 1, null, 'NSPZT', null, null, null, null, null);
insert into OPERATION_DICT (ID, OPERATION_CODE, OPERATION_NAME, OPERATION_SCALE, STD_INDICATOR, APPROVED_INDICATOR, CREATE_DATE, INPUT_CODE, INPUT_CODE_WB, NM2, CREATE_USER, MEMO, OPERATION_TYPE)
values ('E996F802BF5C45DBA82CA18C6F4C90D3', '2.395', '脑室分流术', null, 1, 1, null, 'NSFLS', null, null, null, null, null);
insert into OPERATION_DICT (ID, OPERATION_CODE, OPERATION_NAME, OPERATION_SCALE, STD_INDICATOR, APPROVED_INDICATOR, CREATE_DATE, INPUT_CODE, INPUT_CODE_WB, NM2, CREATE_USER, MEMO, OPERATION_TYPE)
values ('6BAF01B709884F11A246A0303077623B', '2.396', '脑室引流', null, 1, 1, null, 'NSYL', null, null, null, null, null);