CREATE OR REPLACE VIEW V_CLINIC_NAME_DICT AS
SELECT "ORG_ID","ITEM_CLASS","ITEM_NAME","ITEM_CODE","STD_INDICATOR","INPUT_CODE","INPUT_CODE_WB","EXPAND1","EXPAND2","EXPAND3","EXPAND4","EXPAND5"
  FROM clinic_item_name_dict
where item_class <> 'A' and  item_class <> 'B'

