CREATE OR REPLACE TRIGGER DRUG_PRICE_LIST_INSERT
  AFTER INSERT ON DRUG_PRICE_LIST
  REFERENCING NEW AS NEW OLD AS OLD
  FOR EACH ROW
DECLARE
  V_DRUG_INDICATOR NUMBER(1);
  V_DRUG_NAME      VARCHAR2(100);
  V_DRUG_CLASS     VARCHAR2(1);
BEGIN
  SELECT DISTINCT DRUG_INDICATOR
    INTO V_DRUG_INDICATOR
    FROM DRUG_DICT
   WHERE DRUG_CODE = :NEW.DRUG_CODE;

  SELECT DRUG_NAME
    INTO V_DRUG_NAME
    FROM DRUG_NAME_DICT
   WHERE STD_INDICATOR = 1
     AND DRUG_CODE = :NEW.DRUG_CODE;

  IF V_DRUG_INDICATOR = 1 OR V_DRUG_INDICATOR = 2 OR V_DRUG_INDICATOR = 3 OR
     V_DRUG_INDICATOR = 5 OR V_DRUG_INDICATOR = 6 OR V_DRUG_INDICATOR = 9 OR
     V_DRUG_INDICATOR = 8 THEN
    IF V_DRUG_INDICATOR = 1 OR V_DRUG_INDICATOR = 3 OR V_DRUG_INDICATOR = 5 OR
       V_DRUG_INDICATOR = 6 OR V_DRUG_INDICATOR = 9 OR V_DRUG_INDICATOR = 8 THEN
      V_DRUG_CLASS := 'A';
    ELSE
      V_DRUG_CLASS := 'B';
    END IF;

    INSERT INTO PRICE_LIST
      (ID,ITEM_CLASS,
       ITEM_CODE,
       ITEM_NAME,
       ITEM_SPEC,
       UNITS,
       PRICE,
       PREFER_PRICE,
       FOREIGNER_PRICE,
       FEE_TYPE_MASK,
       CLASS_ON_INP_RCPT,
       CLASS_ON_OUTP_RCPT,
       CLASS_ON_RECKONING,
       SUBJ_CODE,
       CLASS_ON_MR,
       MEMO,
       START_DATE,
       ENTER_DATE)
    VALUES
      (sys_guid(),V_DRUG_CLASS,
       :NEW.DRUG_CODE,
       V_DRUG_NAME,
       :NEW.DRUG_SPEC || GET_DRUG_SUPPLIER_ID(:NEW.FIRM_ID,:NEW.org_id),
       :NEW.UNITS,
       :NEW.RETAIL_PRICE,
       :NEW.RETAIL_PRICE,
       :NEW.RETAIL_PRICE,
       0,
       :NEW.CLASS_ON_INP_RCPT,
       :NEW.CLASS_ON_OUTP_RCPT,
       :NEW.CLASS_ON_RECKONING,
       :NEW.SUBJ_CODE,
       :NEW.CLASS_ON_MR,
       :NEW.MEMOS,
       :NEW.START_DATE,
       SYSDATE);

  END IF;

END;