-- drop table LAB_TEST_MASTER cascade constraints;

/*==============================================================*/
/* Table: LAB_TEST_MASTER     检验主记录                                 */
/*==============================================================*/
CREATE TABLE "LAB_TEST_MASTER" (
"ID" VARCHAR2(64 CHAR) not null,
"TEST_NO" VARCHAR2(20  CHAR) NOT NULL ,
"PRIORITY_INDICATOR" NUMBER(1) NULL ,
"PATIENT_ID" VARCHAR2(10  CHAR) NULL ,
"VISIT_ID" NUMBER(2) NULL ,
"WORKING_ID" VARCHAR2(6  CHAR) NULL ,
"EXECUTE_DATE" DATE NULL ,
"NAME" VARCHAR2(20  CHAR) NULL ,
"NAME_PHONETIC" VARCHAR2(16  CHAR) NULL ,
"CHARGE_TYPE" VARCHAR2(8  CHAR) NULL ,
"SEX" VARCHAR2(4  CHAR) NULL ,
"AGE" NUMBER(3) NULL ,
"TEST_CAUSE" VARCHAR2(8  CHAR) NULL ,
"RELEVANT_CLINIC_DIAG" VARCHAR2(80  CHAR) NULL ,
"SPECIMEN" VARCHAR2(8  CHAR) NULL ,
"NOTES_FOR_SPCM" VARCHAR2(100  CHAR) NULL ,
"SPCM_RECEIVED_DATE_TIME" DATE NULL ,
"SPCM_SAMPLE_DATE_TIME" DATE NULL ,
"REQUESTED_DATE_TIME" DATE NULL ,
"ORDERING_DEPT" VARCHAR2(8  CHAR) NULL ,
"ORDERING_PROVIDER" VARCHAR2(20  CHAR) NULL ,
"PERFORMED_BY" VARCHAR2(8  CHAR) NULL ,
"RESULT_STATUS" VARCHAR2(1  CHAR) NULL ,
"RESULTS_RPT_DATE_TIME" DATE NULL ,
"TRANSCRIPTIONIST" VARCHAR2(20  CHAR) NULL ,
"VERIFIED_BY" VARCHAR2(8  CHAR) NULL ,
"COSTS" NUMBER(8,2) NULL ,
"CHARGES" NUMBER(8,2) NULL ,
"BILLING_INDICATOR" NUMBER(1) NULL ,
"PRINT_INDICATOR" NUMBER(1) NULL ,
"SUBJECT" VARCHAR2(40  CHAR) NULL ,
"CONTAINER_CARRIER" VARCHAR2(20  CHAR) NULL ,
"STATUS" VARCHAR2(160  CHAR)  NULL ,
"MEMO" VARCHAR2(160  CHAR) NULL ,
"WARD_CODE" VARCHAR2(20  CHAR) NULL ,
"PHYEXAM_FLAG" VARCHAR2(20  CHAR) NULL ,
"NAYAOTISHI" VARCHAR2(100  CHAR) NULL ,
"JIANYI" VARCHAR2(500  CHAR) NULL ,
"WSW" VARCHAR2(1  CHAR) NULL ,
"SAMPLEID" VARCHAR2(40  CHAR) NULL,
"DEL_FLAG"         NUMBER (1),
   constraint "PK_LAB_TEST_MASTER" primary key (ID)
);
-- Add comments to the table
COMMENT ON TABLE "LAB_TEST_MASTER" IS '检验主记录';
COMMENT ON COLUMN "LAB_TEST_MASTER"."TEST_NO" IS '申请序号';
COMMENT ON COLUMN "LAB_TEST_MASTER"."PRIORITY_INDICATOR" IS '优先标志';
COMMENT ON COLUMN "LAB_TEST_MASTER"."PATIENT_ID" IS '病人标识号';
COMMENT ON COLUMN "LAB_TEST_MASTER"."VISIT_ID" IS '本次住院标识';
COMMENT ON COLUMN "LAB_TEST_MASTER"."WORKING_ID" IS '工作单号';
COMMENT ON COLUMN "LAB_TEST_MASTER"."EXECUTE_DATE" IS '执行日期';
COMMENT ON COLUMN "LAB_TEST_MASTER"."NAME" IS '姓名';
COMMENT ON COLUMN "LAB_TEST_MASTER"."NAME_PHONETIC" IS '姓名拼音';
COMMENT ON COLUMN "LAB_TEST_MASTER"."CHARGE_TYPE" IS '费别';
COMMENT ON COLUMN "LAB_TEST_MASTER"."SEX" IS '性别';
COMMENT ON COLUMN "LAB_TEST_MASTER"."AGE" IS '年龄';
COMMENT ON COLUMN "LAB_TEST_MASTER"."TEST_CAUSE" IS '检验目的';
COMMENT ON COLUMN "LAB_TEST_MASTER"."RELEVANT_CLINIC_DIAG" IS '临床诊断';
COMMENT ON COLUMN "LAB_TEST_MASTER"."SPECIMEN" IS '标本';
COMMENT ON COLUMN "LAB_TEST_MASTER"."NOTES_FOR_SPCM" IS '标本说明';
COMMENT ON COLUMN "LAB_TEST_MASTER"."SPCM_RECEIVED_DATE_TIME" IS '标本采样日期及时间';
COMMENT ON COLUMN "LAB_TEST_MASTER"."SPCM_SAMPLE_DATE_TIME" IS '标本收到日期及时间';
COMMENT ON COLUMN "LAB_TEST_MASTER"."REQUESTED_DATE_TIME" IS '申请日期及时间';
COMMENT ON COLUMN "LAB_TEST_MASTER"."ORDERING_DEPT" IS '申请科室';
COMMENT ON COLUMN "LAB_TEST_MASTER"."ORDERING_PROVIDER" IS '申请医生';
COMMENT ON COLUMN "LAB_TEST_MASTER"."PERFORMED_BY" IS '执行科室';
COMMENT ON COLUMN "LAB_TEST_MASTER"."RESULT_STATUS" IS '结果状态';
COMMENT ON COLUMN "LAB_TEST_MASTER"."RESULTS_RPT_DATE_TIME" IS '报告日期及时间';
COMMENT ON COLUMN "LAB_TEST_MASTER"."TRANSCRIPTIONIST" IS '报告者';
COMMENT ON COLUMN "LAB_TEST_MASTER"."VERIFIED_BY" IS '校对者';
COMMENT ON COLUMN "LAB_TEST_MASTER"."COSTS" IS '费用';
COMMENT ON COLUMN "LAB_TEST_MASTER"."CHARGES" IS '应收费用';
COMMENT ON COLUMN "LAB_TEST_MASTER"."BILLING_INDICATOR" IS '计价标志';
COMMENT ON COLUMN "LAB_TEST_MASTER"."PRINT_INDICATOR" IS '打印标志';
COMMENT ON COLUMN "LAB_TEST_MASTER"."WARD_CODE" IS '护理单元';
COMMENT ON COLUMN "LAB_TEST_MASTER"."NAYAOTISHI" IS '耐药细菌提示';
COMMENT ON COLUMN "LAB_TEST_MASTER"."JIANYI" IS 'LIS建议';
COMMENT ON COLUMN "LAB_TEST_MASTER"."SAMPLEID" IS 'LIS接口主键';
